### ISSUE TITLE
Not installing on Windows

### ISSUE THREAD

**Issue by galagithub** [mgoblin/STC15lib#1]
```
Library Manager: Installing mgoblin/STC15 hardware
Downloading 0% 10% 20% 30% 40% 50% 60% 70% 80%
Unpacking 0% 10%Unpacking...
Library Manager: Warning! Package Mirror: [WinError 267] The directory name is invalid: 'C:\\Users\\dick\\.platformio\\.cache\\tmp\\pkg-installing-vkjio_ji\\examples\\timer\\aux'
Library Manager: Looking for another mirror...
Downloading 0% 10% 20% 30% 40% 50% 60% 70% 80%
Unpacking 0% 10%Unpacking...
Library Manager: Warning! Package Mirror: [WinError 267] The directory name is invalid: 'C:\\Users\\dick\\.platformio\\.cache\\tmp\\pkg-installing-6mor44ir\\examples\\timer\\aux'
Library Manager: Looking for another mirror...
PackageException: Could not install package 'mgoblin/STC15 hardware' for 'windows_amd64' system
```
"aux" is a reserved filename on windows platform, please rename to "auxiliary"

**Comment by mgoblin** [comment]
Fixed in STC lib v0.10.0

**Comment by galagithub** [comment]
@mgoblin can you also update platform.io? it does not know about latest versions.

you need to use "pio pkg publish" as before, latest available version on platform.io is 0.7.0

**Comment by mgoblin** [comment]
> [@mgoblin](https://github.com/mgoblin) can you also update platform.io? it does not know about latest versions.
Platform.io also updated.

**Comment by galagithub** [comment]
> > [@mgoblin](https://github.com/mgoblin) can you also update platform.io? it does not know about latest versions.
> > Platform.io also updated.

Not working, you forgot to include the actual code, only the doc is included. if you need help, drop me a DM.

**Comment by mgoblin** [comment]
Lets try now

And please show lib_deps from your platfromio.ini

I use lib_deps = https://github.com/mgoblin/STC15lib#0.10.0 or lib_deps = mgoblin/STC15 hardware@^0.10.0
both are worked.

**Comment by galagithub** [comment]
> Lets try now
> 
> And please show lib_deps from your platfromio.ini
> 
> I use lib_deps = https://github.com/mgoblin/STC15lib#0.10.0 or lib_deps = mgoblin/STC15 hardware@^0.10.0 both are worked.

`[env:STC15W201S]`
`platform = intel_mcs51`
`board = STC15W201S`
`lib_deps = mgoblin/STC15 hardware@>=0.10.0`

it works with #0.10.0 for some reason

**Comment by mgoblin** [comment]
I try lib_deps = mgoblin/STC15 hardware@>=0.10.0
Its work for me. Version 0.10.1 is downloaded
.pio/build/libdeps/STC15W408AS/STC15 hardware folder contains docs, includes, src 
and my test project is compiled without errors.
I have only linux host and cannot verify on windows os.

Is it works for you?

**Comment by galagithub** [comment]
now it worked.

it took a while for platfom.io to realize there is a new version (it kept downloading the old 0.10.0)

thanks

**Comment by mgoblin** [comment]
I close this issue.

thanks for the quick help with testing.
